### ISSUE TITLE
GetParams error: panic: runtime error: index out of range [3] with length 0

### ISSUE THREAD

**Issue by ziyliu** [blockwatch-cc/tzgo#16]
I'm getting this stack trace error when calling `GetSnapshotIndexCycle`

<pre>encoding/binary.bigEndian.Uint32(...)
    /usr/local/Cellar/go/1.16.6/libexec/src/encoding/binary/binary.go:112
blockwatch.cc/tzgo/tezos.ChainIdHash.Uint32(...)
    ../vendor/blockwatch.cc/tzgo/tezos/hash.go:650
blockwatch.cc/tzgo/tezos.(*Params).ForHeight(0xc0024ef8c0, 0x26c47, 0xc0029537d0)
    ../vendor/blockwatch.cc/tzgo/tezos/protocols.go:309 +0x307
blockwatch.cc/tzgo/rpc.(*Client).GetParams(0xc00267b200, 0x68a6560, 0xc0029537d0, 0x6882f88, 0xc002698888, 0x83595b8, 0x6de7d67, 0x4b)
    ../vendor/blockwatch.cc/tzgo/rpc/constants.go:188 +0x9c
blockwatch.cc/tzgo/rpc.(*Client).GetSnapshotIndexCycle(0xc00267b200, 0x68a6560, 0xc0029537d0, 0x6882f88, 0xc002698888, 0x26, 0x8, 0x0, 0x62863a2)
    ../vendor/blockwatch.cc/tzgo/rpc/rights.go:274 +0x74</pre>

I've logged the inputs and they appear to be reasonable to me `{.."height": 158791, "cycle": 38}`. Note, this is in alphanet by the way.

**Comment by echa** [comment]
This should work again with recent master. 

Alphanet and sandboxes are a bit tricky because the `Params` type tries to be smart about bugs, quirks and changes in cycle length all found on mainnet. I changed the way params are loaded from on-chain constants which now makes sure that chain id is always initialized.

Note: the client holds a copy of most recent params (`client.Params`) and uses it in some places, i.e. to serialize binary operations and observe/monitor for new blocks. If you use any of these features, please init the client before like

```go
c, err := rpc.NewClient("https://rpc.tzstats.com", nil)
if err != nil {
	return err
}
if err := c.Init(ctx); err != nil {
    return err
}
```

Closing this issue for now. Please reopen if the problem still exists in some form.

**Comment by ziyliu** [comment]
Could we cut a release that includes this fix?
