### ISSUE TITLE
rpc.Send() get blocked at res.WaitContext()

### ISSUE THREAD

**Issue by jxu96** [blockwatch-cc/tzgo#26]
Hello,

I am using your marvelous go library (v1.13.3) to interact with my smart contract. 

However, I cannot figure out why my program below got blocked at "wait-for-confirmations" step:  [res.WaitContext(ctx)](https://github.com/blockwatch-cc/tzgo/blob/eb72820af1f3f72ff9524b0e0a38ff8ddfcde575/rpc/run.go#L355)

The operations were actually valid and included in the block but the block observer didn't raise any callback.

Here's my main code:

```go
func main() {
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	tc := NewTzgoContract(ctx)
	tc.WithClient(RpcUrl)
	tc.WithAddress(ContractAddress)
	tc.Load()
	params := NewEntrypointParameters()
	tc.CallEntrypoint(params)
}
```

And the functions:

```go
func NewTzgoContract(ctx context.Context) *TzgoContract {
	tc := &TzgoContract{
		ctx:     ctx,
		c:       nil,
		address: tezos.InvalidAddress,
		con:     nil,
	}
	return tc
}

func (tc *TzgoContract) WithClient(url string) error {
	c_, err := rpc.NewClient(url, nil)
	if err != nil {
		return err
	}
	err = c_.Init(tc.ctx)
	if err != nil {
		return err
	}
	c_.Listen()
	tc.c = c_
	return nil
}

func (tc *TzgoContract) WithAddress(address string) error {
	a_, err := tezos.ParseAddress(address)
	if err != nil {
		return err
	}
	if a_.Type != tezos.AddressTypeContract {
		return fmt.Errorf("Invalid Contract Address")
	}
	tc.address = a_
	return nil
}

func (tc *TzgoContract) Load() error {
	con_ := contract.NewContract(tc.address, tc.c)
	err := con_.Resolve(tc.ctx)
	if err != nil {
		return err
	}
	tc.con = con_
	return nil
}

func (tc *TzgoContract) CallEntrypoint(params EntrypointParameters) error {
	args := params.EncodeArgs()
	opts := params.EncodeOpts() /* rpc.DefaultOptions */
	_, err := tc.con.Call(tc.ctx, args, opts)
	return err
}
```

Thank you.

**Comment by veqtrus** [comment]
The [example code](https://github.com/blockwatch-cc/tzgo/blob/master/examples/transfer) also gets stuck.

**Comment by echa** [comment]
I just merged PR #29 that may fix this issue.

**Comment by echa** [comment]
I consider this fixed with above PR. Please reopen if the problem persists.

**Comment by tylerdmace** [comment]
This doesn't appear to be resolved with v1.15.0. Simple `contract.Call(ctx, args, opts)` never returns a receipt (nor error) even though the operation made it onto the chain.

**Comment by echa** [comment]
Thanks for taking your time to report! When I understand you right, this is a UX issue where you did not call `cli.Listen()` before sending the contract call. It was an intentional choice to have users explicitly start the block observer system as it generates frequent traffic (at each block). I changed that in v1.15.1 which will now activate the observer with the first transaction sent through the `rpc.Send()` function. 

If you don't fancy the block observer running all the time you can inject a fresh observer for each call (or sequence of calls as you like) using the `CallOptions.Observer` parameter and after the call succeeds close the observer again.

**Comment by tylerdmace** [comment]
@echa This was exactly what I needed. Thank you so much, my friend!
