### ISSUE TITLE
Metadata safe RPC

### ISSUE THREAD

**Issue by cryi** [blockwatch-cc/tzgo#30]
Hi, 

not all RPC nodes provide metadata. (e.g. https://mainnet.api.tez.ie) But using [metadata=always](https://github.com/blockwatch-cc/tzgo/blob/2886d0bc961302e6f34c6e6811f5d2471f806154/rpc/block.go#L275) causes RPC to fail. Can we get metadata safe alternative?

I can make PR this. I just want figure out what is best course of action for tzgo so I wont introduce breaking changes. 
Would be ok to introduce functions:
```go
func (c *Client) GetBlockOptionalMetadata(ctx context.Context, id BlockID, collectMetadata string) (*Block, error) {
   var block Block
   u := fmt.Sprintf("chains/main/blocks/%s?metadata=%s", id, collectMetadata)
   ...
}
```

**Comment by echa** [comment]
It seems mainnet.api.tez.io fails with 500 errors even if you don't use the metadata argument, so the problem may be unrelated. AFAIK you can use `metadata=always` on any node type and with any combination of the `--metadata-size-limit` node setting. Hence the current way of doing it should be safe (its a no-op if metadata exists, it instructs the node to re-execute transactions in order to produce receipts if missing).

The problem with extending the RPC client's API is that the metadata arg applies to more than one endpoint. Adding multiple flavors of those calls further clutters the already too complicated API even more. 

If it is really needed I could add this as a client-wide setting and use it in all places that require tx metadata.

**Comment by echa** [comment]
I added a new client option `MetadataMode` (default `MetadataModeUnset`) which you can set to `MetadataModeNever` or `MetadataModeAlways`. The safest and most compatible setting is always because people may configure their nodes in different ways (no limit, default limit, small limit, zero limit) and in each case always returns full metadata without surprises.
