### ISSUE TITLE
val.GetAddress works for "transfer.from" but not "transfer.from_"

### ISSUE THREAD

**Issue by ianeinser** [blockwatch-cc/tzgo#4]
Hi @echa ,

I suppose the val.GetAddress does not support "transfer.from_" ("from" with underscore)

`--- Value2: {{{unary+ list [{binary pair [{prim+ address [] [%from_] <nil>  [] false} {unary+ list [{variadic pair [{prim+ address [] [%to_] <nil>  [] false} {prim+ nat [] [%token_id] <nil>  [] false} {prim+ nat [] [%amount] <nil>  [] false}] [] <nil>  [] false}] [%txs] <nil>  [] false}] [] <nil>  [] false}] [%transfer] <nil>  [] false}} {sequence parameter [{binary Pair [{string parameter [] [] <nil> tz1KfrU5fjFxV6oKn52eu3YnQN2qgtYksRns [] true} {sequence parameter [{binary Pair [{string parameter [] [] <nil> KT1KgzWtUe2dFbp1CnXGWRE73XsjXM7t3G1V [] true} {binary Pair [{int parameter [] [] 0  [] false} {int parameter [] [] 26914851  [] false}] [] <nil>  [] false}] [] <nil>  [] false}] [] <nil>  [] false}] [] <nil>  [] false}] [] <nil>  [] false} 0 map[transfer:[map[from_:tz1KfrU5fjFxV6oKn52eu3YnQN2qgtYksRns txs:[map[amount:26914851 to_:KT1KgzWtUe2dFbp1CnXGWRE73XsjXM7t3G1V token_id:0]]]]]}`

but it works in 

`--- Value1: {{{binary+ pair [{prim+ address [] [%from] <nil>  [] false} {binary pair [{prim+ address [] [%to] <nil>  [] false} {prim+ nat [] [%value] <nil>  [] false}] [] <nil>  [] false}] [%transfer] <nil>  [] false}} {binary Pair [{string parameter [] [] <nil> tz1W7YV9qXtDvB2tPWWueh6KtfWDBmjZchm9 [] true} {binary Pair [{string parameter [] [] <nil> KT1W3VGRUjvS869r4ror8kdaxqJAZUbPyjMT [] true} {int parameter [] [] 1315122  [] false}] [] <nil>  [] false}] [] <nil>  [] false} 0 map[transfer:map[from:tz1W7YV9qXtDvB2tPWWueh6KtfWDBmjZchm9 to:KT1W3VGRUjvS869r4ror8kdaxqJAZUbPyjMT value:1315122]]}`

the difference between both is 
value2 has "`map[transfer:[map`" (there is a "[" between transfer and map)
value1 has "`map[transfer:map`" (there is no "[" between transfer and map)

value2 is from contract that uses list token in the transfer parameter

 Regards,

Ian

**Comment by echa** [comment]
The difference is that Value2 follows the FA2 standard while Value1 is FA1.2 standard. The call interfaces are actually different, see [here](https://gitlab.com/tezos/tzip/-/blob/master/proposals/tzip-12/tzip-12.md#transfer) for FA2 and [here](https://gitlab.com/tezos/tzip/-/blob/master/proposals/tzip-7/tzip-7.md#transfer) for FA1.2.

FA2 allows multiple transfers of multiple different tokens all managed by the same FA2 contract. It also allows transfers issued by an operator on behalf of multiple senders. That's why a FA2 transfer is additionally wrapped in an outer list. In Go the type would be

```go
type FA2Transfer struct {
    Sender   tezos.Address `json:"from_"`
    Txs      []FA2Tx       `json:"txs"`
}

type FA2Tx struct {
    Receiver  tezos.Address `json:"to_"`
    TokenId   BigInt        `json:"token_id"` // note, using custom BigInt type with the special JSON unmarshaler
    Amount    BigInt        `json:"amount"`  // note, using custom BigInt type with the special JSON unmarshaler
}

// FA2 call params are nested, so we use an extra wrapper
type FA2TransferWrapper struct {
	Transfer []FA2Transfer `json:"transfer"`
}

// then decode via this wrapper
var fx FA2TransferWrapper
value.Unmarshal(&fx)

// or alternatively access sender address of the first transfer in the list
sender, ok := value.GetAddress("0.from_")

// access receiver of the first transfer
tid, ok := value.GetAddress("0.txs.0.to_")
```

We'll add Go type definitions for such standards to TzGo in a future release. One issue to be aware of is that not all contracts are standard compliant. e.g. some FA2 call sender `from` instead of `from_` (and other fun things).
